from .household1 import *
from .household2 import *
from .household3 import *
from .household4 import *
from .household5 import *
from .household6 import *
from .household7 import *
from .household8 import *
from .household9 import *
from .household10 import *
from .lab1 import *
from .lab2 import *
from .lab3 import *
from .lab4 import *
from .lab5 import *
from .lab6 import *
from .lab7 import *
from .lab8 import *
from .lab9 import *
from .lab10 import *
from .cooking1 import *
from .cooking2 import *
from .cooking3 import *
from .cooking4 import *
from .cooking5 import *
from .cooking6 import *
from .cooking7 import *
from .cooking8 import *
from .cooking9 import *
from .cooking10 import *